<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_BNI2</name>
   <tag></tag>
   <elementGuidId>542445d0-0062-4bd6-a0a7-066af22c7ca5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href='#/bank-transfer/bni-va']/div[@class='payment-page-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@href='#/bank-transfer/bni-va']/div[@class='payment-page-text']</value>
      <webElementGuid>d3cef6f1-e075-4a0d-9194-180cc497ab5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Frame/Iframe</value>
      <webElementGuid>8130f2bb-3202-446e-9a06-8d451dc46335</webElementGuid>
   </webElementProperties>
</WebElementEntity>
