<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_mandiri2</name>
   <tag></tag>
   <elementGuidId>9bb9a309-1439-4551-a384-dfec55dcfe8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href='#/bank-transfer/mandiri-va']/div[@class='payment-page-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@href='#/bank-transfer/mandiri-va']/div[@class='payment-page-text']</value>
      <webElementGuid>974f8b8f-7c8c-4d79-9e10-d1db7c24d5e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Frame/Iframe</value>
      <webElementGuid>f2b11a8a-9d23-4bae-8766-4d1c174f7cde</webElementGuid>
   </webElementProperties>
</WebElementEntity>
